# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: aws-s3 0.6.4 ruby lib

Gem::Specification.new do |s|
  s.name = "aws-s3"
  s.version = "0.6.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["marcel"]
  s.date = "2015-10-23"
  s.description = "AWS::S3 is a Ruby library for Amazon's Simple Storage Service's REST API [aws.amazon.com/s3]. Full documentation of the currently supported API can be found at docs.amazonwebservices.com/AmazonS3/2006-03-01."
  s.email = "marcel@vernix.org"
  s.executables = ["s3sh", "setup.rb"]
  s.extra_rdoc_files = [
    "README.erb",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "COPYING",
    "INSTALL",
    "README.erb",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/s3sh",
    "bin/setup.rb",
    "lib/aws/s3.rb",
    "lib/aws/s3/acl.rb",
    "lib/aws/s3/authentication.rb",
    "lib/aws/s3/base.rb",
    "lib/aws/s3/bittorrent.rb",
    "lib/aws/s3/bucket.rb",
    "lib/aws/s3/connection.rb",
    "lib/aws/s3/error.rb",
    "lib/aws/s3/exceptions.rb",
    "lib/aws/s3/extensions.rb",
    "lib/aws/s3/logging.rb",
    "lib/aws/s3/object.rb",
    "lib/aws/s3/owner.rb",
    "lib/aws/s3/parsing.rb",
    "lib/aws/s3/response.rb",
    "lib/aws/s3/service.rb",
    "lib/aws/s3/version.rb",
    "site/index.erb",
    "site/public/images/box-and-gem.gif",
    "site/public/images/favicon.ico",
    "site/public/ruby.css",
    "site/public/screen.css",
    "support/faster-xml-simple/COPYING",
    "support/faster-xml-simple/README",
    "support/faster-xml-simple/Rakefile",
    "support/faster-xml-simple/lib/faster_xml_simple.rb",
    "support/faster-xml-simple/test/fixtures/test-1.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-1.xml",
    "support/faster-xml-simple/test/fixtures/test-1.yml",
    "support/faster-xml-simple/test/fixtures/test-2.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-2.xml",
    "support/faster-xml-simple/test/fixtures/test-2.yml",
    "support/faster-xml-simple/test/fixtures/test-3.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-3.xml",
    "support/faster-xml-simple/test/fixtures/test-3.yml",
    "support/faster-xml-simple/test/fixtures/test-4.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-4.xml",
    "support/faster-xml-simple/test/fixtures/test-4.yml",
    "support/faster-xml-simple/test/fixtures/test-5.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-5.xml",
    "support/faster-xml-simple/test/fixtures/test-5.yml",
    "support/faster-xml-simple/test/fixtures/test-6.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-6.xml",
    "support/faster-xml-simple/test/fixtures/test-6.yml",
    "support/faster-xml-simple/test/fixtures/test-7.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-7.xml",
    "support/faster-xml-simple/test/fixtures/test-7.yml",
    "support/faster-xml-simple/test/fixtures/test-8.rails.yml",
    "support/faster-xml-simple/test/fixtures/test-8.xml",
    "support/faster-xml-simple/test/fixtures/test-8.yml",
    "support/faster-xml-simple/test/regression_test.rb",
    "support/faster-xml-simple/test/test_helper.rb",
    "support/faster-xml-simple/test/xml_simple_comparison_test.rb",
    "support/rdoc/code_info.rb",
    "test/acl_test.rb",
    "test/authentication_test.rb",
    "test/base_test.rb",
    "test/bucket_test.rb",
    "test/connection_test.rb",
    "test/error_test.rb",
    "test/extensions_test.rb",
    "test/fixtures.rb",
    "test/fixtures/buckets.yml",
    "test/fixtures/errors.yml",
    "test/fixtures/headers.yml",
    "test/fixtures/logging.yml",
    "test/fixtures/loglines.yml",
    "test/fixtures/logs.yml",
    "test/fixtures/policies.yml",
    "test/logging_test.rb",
    "test/mocks/fake_response.rb",
    "test/object_test.rb",
    "test/parsing_test.rb",
    "test/remote/acl_test.rb",
    "test/remote/bittorrent_test.rb",
    "test/remote/bucket_test.rb",
    "test/remote/logging_test.rb",
    "test/remote/object_test.rb",
    "test/remote/test_file.data",
    "test/remote/test_helper.rb",
    "test/response_test.rb",
    "test/service_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/marcel/aws-s3"
  s.rubyforge_project = "amazon"
  s.rubygems_version = "2.4.6"
  s.summary = "Ruby implementation of Amazon's S3 REST API"
end

